import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Bars/Navbar";
import Footer from "@/components/ui/Bars/Footer";

const poppinsFonds = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFonds.variable} ${poppinsFonds.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <div>
          {children}
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
