import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AdminMainBar from "@/components/ui/Bars/AdminMainBar";

const poppinsFonds = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFonds.variable} ${poppinsFonds.variable} antialiased`}
      >
        <div className="w-full h-full relative">
          <div className="pt-[80px] pl-[150px]">
            {children}
          </div>
          <AdminMainBar />
        </div>
      </body>
    </html>
  );
}
